"""Split the opening clusters in two, before anything is selected on either half.

The holdout was generated by playing games out of `audit/ab-openings.json`, and the
acceptance match wants to play games out of it too. Using the whole set for both would let
a network be chosen on positions downstream of the very openings it is then measured from,
which is a leak even though nothing was trained on them.

So the clusters are partitioned once, deterministically, by a hash of the cluster name.
One half keeps its holdout positions and is what the pilot is judged on. The other half
becomes the acceptance opening set and nothing is ever selected on it.

    uv run python audit/next-strength/run1/split.py
"""

import hashlib
import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent


def side(cluster: str) -> str:
    """Which half a cluster falls in. A hash, so the split does not follow the sort order."""
    digest = hashlib.sha256(f"run1:{cluster}".encode()).digest()
    return "eval" if digest[0] & 1 else "acceptance"


def main() -> int:
    openings = json.loads((ROOT / "audit" / "ab-openings.json").read_text())["positions"]
    holdout = json.loads((HERE / "holdout.json").read_text())

    clusters = {str(row["cluster"]) for row in openings}
    halves = {name: side(name) for name in clusters}
    acceptance = [row for row in openings if halves[str(row["cluster"])] == "acceptance"]
    kept = [row for row in holdout["positions"] if halves.get(str(row["cluster"])) == "eval"]

    (HERE / "openings-acceptance.json").write_text(
        json.dumps({"positions": acceptance,
                    "note": "acceptance half of audit/ab-openings.json; nothing is selected "
                            "on these clusters"}, indent=1) + "\n"
    )
    holdout["provenance"]["split"] = "eval half only; see audit/next-strength/run1/split.py"
    holdout["positions"] = kept
    (HERE / "holdout-eval.json").write_text(json.dumps(holdout, indent=1) + "\n")

    counts: dict[str, int] = {}
    for value in halves.values():
        counts[value] = counts.get(value, 0) + 1
    summary: dict[str, Any] = {
        "clusters": counts,
        "acceptance_openings": len(acceptance),
        "acceptance_clusters": len({r["cluster"] for r in acceptance}),
        "holdout_positions": len(kept),
        "holdout_clusters": len({r["cluster"] for r in kept}),
    }
    print(json.dumps(summary, indent=1))
    (HERE / "split.json").write_text(json.dumps(summary, indent=1) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
