"""Export what the C++ engine in cpp/ needs from the Python one.

    net      weights/net.npz as a flat little-endian blob, which the build embeds in the
             binary so it carries its network with it
    zobrist  bitboard.py's Zobrist keys as a C++ include, so both engines hash every
             position identically and a fixed-node search can be compared node for node

The npz is deflate-compressed, and reading zip in C++ means either zlib at runtime or a zip
parser in the engine. A flat blob written here needs neither.

Blob layout, every field little-endian:

    b"NNUE", uint32 version, uint32 L1, uint32 buckets, int32 qa, int32 qb, int32 scale
    int16 ft_weight[768][L1], int16 ft_bias[L1], int16 out_weight[buckets][2 * L1],
    int32 out_bias[buckets]
"""

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

NET_MAGIC = b"NNUE"
NET_VERSION = 1


def export_net(source: Path, destination: Path) -> None:
    with np.load(source) as data:
        ft_weight = data["ft_weight"].astype("<i2")
        ft_bias = data["ft_bias"].astype("<i2")
        out_weight = data["out_weight"].astype("<i2")
        out_bias = data["out_bias"].astype("<i4")
        qa, qb, scale = int(data["qa"]), int(data["qb"]), int(data["scale"])
    hidden = ft_bias.shape[0]
    buckets = out_bias.shape[0]
    if ft_weight.shape != (768, hidden) or out_weight.shape != (buckets, 2 * hidden):
        raise ValueError(f"{source} has an unexpected shape: {ft_weight.shape}, {out_weight.shape}")
    header = NET_MAGIC + struct.pack("<IIIiii", NET_VERSION, hidden, buckets, qa, qb, scale)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("wb") as out:
        out.write(header)
        for array in (ft_weight, ft_bias, out_weight, out_bias):
            out.write(np.ascontiguousarray(array).tobytes())


def _row(values: np.ndarray) -> str:
    return ", ".join(f"0x{int(v):016X}ull" for v in values)


def export_zobrist(destination: Path) -> None:
    from bitboard import Z_CASTLE, Z_EP, Z_PIECE, Z_STM

    lines = [
        "// Generated by `tools/export_cpp.py zobrist`: the Python engine's Zobrist keys, so",
        "// the two engines hash every position identically. Do not edit by hand.",
        "",
        "inline constexpr Key ZOBRIST_PIECE[2][6][64] = {",
    ]
    for colour in range(2):
        lines.append("    {")
        for piece in range(6):
            lines.append(f"        {{{_row(Z_PIECE[colour, piece])}}},")
        lines.append("    },")
    lines += [
        "};",
        f"inline constexpr Key ZOBRIST_STM = 0x{int(Z_STM[0]):016X}ull;",
        f"inline constexpr Key ZOBRIST_CASTLE[16] = {{{_row(Z_CASTLE)}}};",
        f"inline constexpr Key ZOBRIST_EP[8] = {{{_row(Z_EP)}}};",
        "",
    ]
    destination.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    net = commands.add_parser("net", help="write the network blob")
    net.add_argument("out", type=Path)
    net.add_argument("--source", type=Path, default=ROOT / "weights" / "net.npz")
    zobrist = commands.add_parser("zobrist", help="write the Zobrist key include")
    zobrist.add_argument("out", type=Path)
    arguments = parser.parse_args()

    if arguments.command == "net":
        export_net(arguments.source, arguments.out)
    else:
        export_zobrist(arguments.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
